spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/healthapp?options=-c%20TimeZone=Asia/Kolkata}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:health}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:health}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${SERVER_PORT:8080}
