spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/healthapp?options=-c%20TimeZone=Asia/Kolkata}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:health}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:health}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${SERVER_PORT:8080}

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB
gemini.model=gemini-2.5-flash
gemini.api-key=AIzaSyDlLP1HbUoh2u6D8-EDF4AHyH5dgotx8DY
